### ISSUE TITLE
Provide the option to skip SSL verification for requests

### ISSUE THREAD

**Issue by Futsch1** [jesper-raemaekers/python-polarion#34]
If Polarion is used with an HTTPS connection using a self-signed certificate, some workarounds are required to make the requests package skip the certificate verification.

It would be nice to have a kwarg for the Polarion object constructor that disables SSL verification.

**Comment by jesper-raemaekers** [comment]
Sounds good. Did you try a workaround? 
I looked [here](https://2.python-requests.org/en/master/user/advanced/#ssl-cert-verification) and it looks like i only need to pass verify=False when it's used.

**Comment by Futsch1** [comment]
Exactly, that's what needs to be done - I can also prepare a PR if you prefer and test it on my environment.

Currently, I am using a fairly complicated workaround overwriting requests.Session.merge_environment_settings, which is fairly ugly.

Additionally, I can also support you in terms of document support if you want (I currently have a use case related to reusing documents via the web service which I'd like to do with the help of your package).

**Comment by jesper-raemaekers** [comment]
Thanks! I will merge it, but it might take a little since I'm currently moving and have limited time.

For the document support i made a start, so feel free to continue: https://github.com/jesper-raemaekers/python-polarion/tree/documents

Currently it's a draft, so feel free to change anything. The class name currently is module, but i think it should be renamed to document. Module seems to be an old Polarion thing. Here is a snippet of how i was testing it locally:
```

spaces = project.getDocumentSpaces()
# spaces = project.getDocumentLocations()
docs = project.getDocumentsInSpace(spaces[0])
# workitem_in_doc = docs[0].getWorkItems()
comment = docs[0].comments.ModuleComment[0].uri
workitems = docs[0].getWorkItems()
# docs[0].insertComment('Hello this is a document comment')
top_level = docs[0].getTopLevelWorkitem()
docs[0].insertCommentReply(comment, 'Reply!')
```
