### ISSUE TITLE
[Question] usage of suds vs zeep

### ISSUE THREAD

**Issue by leelavg** [jesper-raemaekers/python-polarion#39]
Hi @jesper-raemaekers,

- I only skimmed through the code and found the implementation is clean, congrats for that.
- My question is, before picking up Zeep did you try Suds as well and how well Zeep is generating WSDL services, since polarion is not a trivial service 😅
- If you indeed did any POC, did you see the speed improvements in zeep vs suds?

Why am I asking?
- By any means I'm not demotivating the effort and at the same time couldn't resist opening the dialogue about duplicate effort 😄
- We have an open source [project](https://github.com/RedHatQE/pylero) which also provides Python API for Polarion and I'm here out of technical interest on how good it'd be to swap Suds with Zeep.

Repeating again, I'm here to get to know zeep ability of generating wsdl objects natively from your experience. If you feel the question/premise is inappropriate, please close and delete the issue.

Thanks.

**Comment by jesper-raemaekers** [comment]
Hi @leelavg ,

I can only appreciate the question, so no worries there. It is also good to see (find) another project with comparable goals as I could not find it before creating this project.

As for your actual question, I did not compare suds with zeep before i started and that mainly has to do with the sample i started with at some point. This https://gist.github.com/3mb3dw0rk5/1f8868dceac8e40226bc360abac7c9ad snippet uses zeep and I never looked at anything else because it just looked good enough. 
The only complaint i have is that there seems to be some time wasted in zeep. If i look at the profile results of the unit tests then this is currently the top bit of the results:
![image](https://user-images.githubusercontent.com/76244626/143734635-1f7b5e2a-6a55-427c-91c2-d858f2ca6823.png)
And while i can see while a receive method would be there it seems to me like it is unnecessary amount of getaddrinfo calls in second place. I never looked at the details, but this feels like an option for optimizations.

Working with zeep i found that it generates a pretty predictable result for the WSDL API and only the optional argument (the ones where null/none is allowed) need an extra statement.


Kind regards,

**Comment by leelavg** [comment]
@jesper-raemaekers 

- Thanks a lot for detailed info
- Regarding profiling I suspect client refreshes SOAP connections and at the same, I agree that can be an optimisation
- Currently for Pylero I think Suds is a bottleneck, don't want to change it much as Pylero is being used from more than 6 yrs and mostly receiving bug fixes to support latest Polarion releases 
- So, will keep an eye on this project and see if I can contribute here, happy hacking 😀

**Comment by leelavg** [comment]
One last question if you don't mind.

- How are running tests without Polarion instance 
- I don't see any github actions but can see mention of Azure so do you test against any running instance somewhere?

**Comment by jesper-raemaekers** [comment]
We are running tests against a Polarion instance. The only goals for the Polarion insatnce here is to be a data dump basically. There is a project which is a complete mess with generated workitems and test runs. I think it's public on DevOps too, so you should be able to view this: https://dev.azure.com/jraemaekers/Python%20Polarion/_build/results?buildId=199&view=results
