### ISSUE TITLE
inserting a test step 

### ISSUE THREAD

**Issue by tblock-zz** [jesper-raemaekers/python-polarion#40]
Hello,
I tried to modify a test step in polarion by changing the attribute of a work item and saved it afterwards.
But the changes are not saved.
E.g.
wi = polarion.Polarion('http...', 'MyUserid', 'MyPassword').getProject('MyProjectName').getWorkitem('MyWorkitem')
wi._polarion_test_steps['steps']['TestStep'][0]['values']['Text'][1]['content']='\xa0description1'
wi.save()

Now I would expect that the first entry in the "Test Steps" in Table Entry "Step Description" would have been updated.
But that did not happen.
Did I just made it wrong or used the wrong attribute?
Sorry I also did not found anything in the descriptions.

**Comment by jesper-raemaekers** [comment]
Hi @tblock-zz ,

This is not yet supported yet, but i have a workaround for you.

```
# getting the workitem and updating the test step
wi = project.getWorkitem('PYTH-1467')
wi._polarion_test_steps.steps.TestStep[0].values.Text[1].content = 'New description!'

# getting the test management service and saving the test steps
service = client.getService('TestManagement')
service.setTestSteps(wi.uri, wi._polarion_test_steps.steps.TestStep)

#reload workitem so it's in sync
wi._reloadFromPolarion()
```

The issue is that the tests steps are not loaded from the same service. So you'd have to save them using this method. Good job finding this and it will be added in the future. If you have any other question feel free the reopen the ticket.
