### ISSUE TITLE
How to Log in Polarion with SSO configured

### ISSUE THREAD

**Issue by schallinterferenz** [jesper-raemaekers/python-polarion#96]
Hello, 

I'm trying to Log into Polarion using your Lib. I face the problem, that if I login into Polarion with Username and Token, it throws this error message.

`Polarion Error: Cannot login because WSDL has no SessionWebService`

I couldn't find any appropriate fix for this error, so maybe you know what is the fault here. 

Greets

**Comment by jesper-raemaekers** [comment]
This happens when the polarion url '<your domain>/polarion/ws/services' cannot be found. You could check if the page is there, but regardless you can try setting static_service_list  to True in the polarion constructor. [docs](https://python-polarion.readthedocs.io/en/latest/polarion_client.html#polarion.polarion.Polarion)

**Comment by schallinterferenz** [comment]
Thank you for your answer. We figured out that we had to remove the part after '.../polarion/' in our link. Now it works.
